Alberta age credit.
PolicyEngine/policyengine-canada pull request #291
Opened 2023-05-24 02:24 UTC by oliviacaiww

Fixes #276

2023-07-11 02:41 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    fixed:
```suggestion
    added:
```

2023-07-11 02:41 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +- bump: patch
```suggestion
- bump: minor
```

2023-07-11 02:41 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/age_credit/base.yaml
> +
```suggestion
```

2023-07-11 02:41 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/age_credit/base.yaml
> +
```suggestion
```

2023-07-11 02:42 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/age_credit/eligible_age.yaml
> +description: Alberta allows people above this age to receive the age credit.
```suggestion
description: Alberta provides the age credit to filers above this age threshold.
```

2023-07-11 02:42 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/age_credit/phase_out_rate.yaml
> +
```suggestion
```

2023-07-11 02:42 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/age_credit/phase_out_rate.yaml
> +
```suggestion
```

2023-07-11 02:42 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/age_credit/phase_out_rate.yaml
> +
```suggestion
```

2023-07-11 02:43 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/age_credit/ab_age_credit_eligible_count.py
dont need this as it is all person level

2023-07-11 02:43 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/age_credit/ab_age_credit.py
> +        eligibility = Person("ab_age_credit_eligible_count", period)
```suggestion
        eligibility = Person("ab_age_credit_eligibility", period)
```

2023-07-11 02:44 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/age_credit/ab_age_credit.py
> +        benefit_amount = select(
```suggestion
        return = where(eligible,  prebenefit * eligibility, 0)
```

2023-08-08 14:53 UTC, PavelMakarchuk approved these changes

2023-08-10 00:47 UTC, MaxGhenis requested changes

2023-08-10 00:47 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/age_credit/ab_age_credit_eligibile.py
> +class ab_age_credit_eligibile(Variable):
```suggestion
class ab_age_credit_eligible(Variable):
```

2023-08-11 04:31 UTC, MaxGhenis approved these changes

2023-08-11 04:31 UTC, merged