Yukon basic personal amount
PolicyEngine/policyengine-canada pull request #313
Opened 2023-05-29 22:26 UTC by RuoqiTan

fixes #312

2023-07-01 21:21 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
this calculation is only applicable if the applicants income is more than $165,430 - if it is below the BPA is $13,521 flat.

2023-07-01 21:21 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
please include that clause

2023-07-01 21:22 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/income_threshold.yaml
> +description: Yukon uses this income threshold for the basic personal amount.
```suggestion
description: Yukon provides a calculation for the basic personal amount for filer with income above this threshold.
```

2023-07-01 21:23 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +description: Yukon uses this base amount for the basic personal amount.
```suggestion
description: Yukon provides this base amount under the basic personal amount.
```

2023-07-01 21:23 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.yaml
> +    yt_basic_personal_amount: 0
```suggestion
    yt_basic_personal_amount: 13_521
```

2023-07-03 22:25 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
could you please add the legal source

2023-07-03 22:26 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
need to find the right page [here](https://laws.yukon.ca/cms/images/LEGISLATION/PRINCIPAL/2002/2002-0118/2002-0118.pdf)

2023-07-03 22:29 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +  2023-01-01: 13_521
```suggestion
  2023-01-01: 15_000
```

2023-07-03 22:29 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1yt-ws/td1yt-ws-23e.pdf
add [this](https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1yt/td1yt-23e.pdf) source

2023-07-17 22:18 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +  - title: Income Tax Act
add the exact part of the income tax act (paragraph, x...)

2023-07-17 22:18 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +  - title: Income Tax Act
all yaml files

2023-07-17 22:19 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +    href: https://laws.yukon.ca/cms/images/LEGISLATION/PRINCIPAL/2002/2002-0118/2002-0118.pdf
add page to link

2023-07-17 22:19 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +    href: https://laws.yukon.ca/cms/images/LEGISLATION/PRINCIPAL/2002/2002-0118/2002-0118.pdf
all yaml files

2023-07-17 22:24 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +description: Yukon uses this applicable amount for the basic personal amount.
```suggestion
description: Yukon provides this applicable amount for the basic personal amount.
```

2023-07-17 22:25 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
Could you make a folder called "reduction" and then put all the files in it that are not the base amount

2023-07-17 22:26 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +        percent = max_(0, (p.scale_value - exceedance) / p.scale_value)
break this formula up

2023-07-17 22:27 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +        exceedance = income - p.income_threshold
if the person has income of under $165,430 they just get the main $13,521 - we need to account for that

2023-07-19 20:41 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/reduction/applicable_amount.yaml
> +  - title: Income Tax Act
add specific part of the legislation and add it to all the parameters

2023-07-19 20:41 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +            (percent * p.reduction.applicable_amount) * eligible
separate formula

2023-07-22 15:36 UTC, MaxGhenis requested changes
I'd suggest consolidating this into a single scale parameter which starts at `15_000` at income `0`, then phases out at a rate of `1_479 / 70_245` at income of `165_430`, then changes to a `0` rate at `165_430 + 70_245`

2023-08-03 02:32 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +        income = person("individual_net_income", period)
need to check for is_head

2023-08-08 21:49 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +        income = person("individual_net_income", period)
no longer right

2023-08-08 21:55 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +        income = person("individual_net_income", period)
No, we do not

2023-08-08 21:55 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +        head = person("is_head", period)
```suggestion
```

2023-08-08 21:55 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +        head = person("is_head", period)
my bad, we dont need to check that

2023-08-08 21:55 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.py
> +        return (base + reduction) * head
```suggestion
        return (base + reduction) 
```

2023-08-20 19:28 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/basic_personal_amount.yaml
> +  - title: 2023 Yukon Personal Tax Credits Return
need Yukon income tax act reference

2023-08-20 19:28 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/basic_personal_amount.yaml
> +  label: Yukon basic personal amount for people with net income less than income threshold
```suggestion
  label: Yukon basic personal amount 
```

2023-08-20 19:28 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/basic_personal_amount.yaml
> +description: Yukon provides this basic personal amount for people with net income less than income threshold.
```suggestion
description: Yukon credits this basic personal amount.
```

2023-08-28 20:10 UTC, PavelMakarchuk commented
> 



> I'd suggest consolidating this into a single scale parameter which starts at `15_000` at income `0`, then phases out at a rate of `1_479 / 70_245` at income of `165_430`, then changes to a `0` rate at `165_430 + 70_245`

Not sure if I understood this correctly, but it seems like there has to be some logic implemented before we can support this right?

2023-09-11 22:12 UTC, closed without merging