Canada Employment Benefit
PolicyEngine/policyengine-canada pull request #323
Opened 2023-06-05 22:49 UTC by sqw0418

Fixes #322

2023-08-02 23:01 UTC, PavelMakarchuk approved these changes

2023-08-03 03:37 UTC, MaxGhenis requested changes

2023-08-03 03:37 UTC, MaxGhenis commented on policyengine_canada/variables/gov/cra/tax/income/credits/canada_employment_amount.py
> +        employment_income = person("employment_income", period)
Make an `income_sources` parameter file with employment_income and other_employment_income
```suggestion
        countable_income = add(person, period, p.income_sources)
```

2023-08-03 03:37 UTC, MaxGhenis commented on policyengine_canada/variables/gov/cra/tax/income/credits/canada_employment_amount.py
> +        max_amount = parameters(
and remove `.max_amount`
```suggestion
        p = parameters(
```

2023-08-03 03:37 UTC, MaxGhenis commented on policyengine_canada/variables/gov/cra/tax/income/credits/canada_employment_amount.py
> +
```suggestion
        # While the government website states that the Canada Employment Amount is designed
        # to support workers with work-related expenses, those expenses are not part of the formula.
```

2023-08-07 22:22 UTC, PavelMakarchuk approved these changes

2023-08-07 23:01 UTC, MaxGhenis requested changes

2023-08-07 23:01 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/cra/tax/income/credits/canada_employment_amount/max_amount.yaml
> +  - title: Canada Income Tax Act, 118 (10) - Canada employment credit
```suggestion
  # The law specifies $1,000.
  - title: Canada Income Tax Act, 118 (10) - Canada employment credit
```

2023-08-09 18:36 UTC, MaxGhenis requested changes

2023-08-09 18:36 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/cra/tax/income/credits/canada_employment_amount/max_amount.yaml
> +
```suggestion
values:
```

2023-08-09 18:36 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/cra/tax/income/credits/canada_employment_amount/income_sources.yaml
> +lues:
```suggestion
values:
```

2023-08-09 23:04 UTC, MaxGhenis approved these changes

2023-08-09 23:04 UTC, merged