Nova Scotia Basic personal amount
PolicyEngine/policyengine-canada pull request #407
Opened 2023-07-17 22:00 UTC by okeyiii

Fixed #395

2023-07-19 20:43 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/additional_amount.yaml
> +description: Nova Scotia additional amount in basic personal amount.
```suggestion
description: Nova Scotia provides this additional amount under the basic personal amount.
```

2023-07-19 20:43 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/additional_amount.yaml
> +description: Nova Scotia additional amount in basic personal amount.
similar format in all yaml descriptions

2023-07-19 20:43 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_basic_personal_credits.py
> +        return select(
separate the formula out in steps for readability

2023-07-24 01:27 UTC, Yaohhhh commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/basic_amount.yaml
> +description: Nova Scotia basic amount in basic personal amount.
Change this description to be:
Nova Scotia provides this basic amount under basic personal amount.

2023-07-24 01:28 UTC, Yaohhhh commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/applicable_rate.yaml
> +description: Nova Scotia applicable rate for calculating partial basic personal amount in basic personal amount.
Change the description to be:
Nova Scotia employs this applicable rate for calculating partial basic personal amounts.

2023-07-24 01:30 UTC, Yaohhhh commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/higher_income_threshold.yaml
> +description: Nova Scotia higher income threshold for minimum basic personal amount in basic personal amount.
Change to:
Nova Scotia limits this higher income threshold under the basic personal amount eligibility.

2023-07-24 01:30 UTC, Yaohhhh commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/lower_income_threshold.yaml
> +description: Nova Scotia lower income threshold for maximum basic personal amount in basic personal amount.
Change to:
Nova Scotia limits this lower income threshold under the basic personal amount eligibility.

2023-07-26 08:48 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/basic_amount.yaml
> +  - title: Nova Scotia Basic Personal Amount
change to: Worksheet NS428

2023-07-26 08:48 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/higher_income_threshold.yaml
> +  - title: Nova Scotia Basic Personal Amount
change to: Worksheet NS428

2023-07-26 08:48 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/lower_income_threshold.yaml
> +  - title: Nova Scotia Basic Personal Amount
change to: Worksheet NS428

2023-07-26 08:49 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/additional_amount.yaml
> +  - title: Nova Scotia Basic Personal Amount
change to: Worksheet NS428

2023-07-26 08:50 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/additional_amount.yaml
> +  - title: Nova Scotia Basic Personal Amount
change to: 2022 Nova Scotia Personal Tax Credits Return

2023-07-26 08:50 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/applicable_rate.yaml
> +  - title: Nova Scotia Basic Personal Amount
change to: 2022 Nova Scotia Personal Tax Credits Return

2023-07-26 08:50 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/higher_income_threshold.yaml
> +  - title: Nova Scotia Basic Personal Amount
change to: 2022 Nova Scotia Personal Tax Credits Return

2023-07-26 08:50 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/lower_income_threshold.yaml
> +  - title: Nova Scotia Basic Personal Amount
change to: 2022 Nova Scotia Personal Tax Credits Return

2023-07-26 08:52 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/additional_amount.yaml
change folder's name "ns_basic_personal_amount" to "basic_personal_amount".

2023-07-26 08:57 UTC, Snownow0w commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/applicable_rate.yaml
> +  unit: \1
change to:
  unit: currency-CAD
  period: year
  rate_unit: /1

2023-07-26 08:58 UTC, Snownow0w commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_basic_personal_credits.py
> +
add reference

2023-07-26 09:06 UTC, Snownow0w reviewed
Some comments about NS Basic Personal Amount

2023-08-01 00:47 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +- bump: patch
```suggestion
- bump: minor
```

2023-08-01 00:47 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Chage names to proper expressions for title, label, reference and folder.
```suggestion
    - Nova Scotia Basic Personal Amount.
```

2023-08-01 00:47 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Make format.
```suggestion
```

2023-08-01 00:47 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Make format.
We only need to add the changelog entry once

2023-08-01 00:52 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/additional_amount.yaml
make an additional_amount folder and include all the files that are not the base

2023-08-01 00:52 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/basic_amount.yaml
rename to `base.yaml`

2023-08-01 00:53 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/basic_amount.yaml
> +description: Nova Scotia provides this basic amount under basic personal amount.
```suggestion
description: Nova Scotia provides this base amount under the basic personal amount.
```

2023-08-01 00:53 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/basic_amount.yaml
> +  label: Nova Scotia Basic Personal Amount
```suggestion
  label: Nova Scotia Basic Personal Amount
```
```suggestion
  label: Nova Scotia Basic Personal Amount base
```

2023-08-01 00:53 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/higher_income_threshold.yaml
dont need this as it is mathematically derived

2023-08-01 00:56 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/lower_income_threshold.yaml
> +description: Nova Scotia limits this lower income threshold under the basic personal amount eligibility.
```suggestion
description: Nova Scotia phases its additional basic personal amount out for filers with income above this threshold.
```

2023-08-01 00:56 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/lower_income_threshold.yaml
> +  label: Nova Scotia Basic Personal Amount Lower Income Threshold
```suggestion
  label: Nova Scotia Basic Personal Amount additional amount phase out start
```

2023-08-01 00:57 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/additional_amount.yaml
> +  label: Nova Scotia Additional Personal Amount
```suggestion
  label: Nova Scotia basic personal amount additional amount
```

2023-08-01 00:57 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/additional_amount.yaml
> +  label: Nova Scotia Additional Personal Amount
All lower case besides state in label

2023-08-01 00:57 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/applicable_rate.yaml
> +description: Nova Scotia employs this applicable rate for calculating partial basic personal amounts.
```suggestion
description: Nova Scotia reduces its additional basic personal amount out at this rate.
```

2023-08-01 00:58 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/applicable_rate.yaml
> +  label: Nova Scotia Basic Personal Amount Applicable Rate
```suggestion
  label: Nova Scotia Basic Personal Amount reduction Rate
```

2023-08-01 00:58 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/basic_personal_credits.py
> +        lower_income_condition = taxable_income <= p.lower_income_threshold
```suggestion
        income_threshold = taxable_income <= p.lower_income_threshold
```

2023-08-01 00:59 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/basic_personal_credits.py
> +        higher_income_condition = taxable_income >= p.higher_income_threshold
```suggestion
```

2023-08-01 01:01 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/basic_personal_credits.py
> +        lower_basic_personal_amount = p.additional_amount + p.basic_amount
try to follow the [worksheet](https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5003-d/5003-d-22e.pdf) as a step by step -> take base, take add. amount, take income, check for threshold, multiply by rate cap at max amount

2023-08-01 01:02 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount/basic_amount.yaml
need a file called `max_amount` representing the 11,481 from form: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5003-d/5003-d-22e.pdf

2023-08-03 02:33 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/basic_personal_credits.py
> +            p.basic_amount
need to check for is_head

2023-08-03 02:33 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/basic_personal_credits.py
> +class ns_basic_personal_credits(Variable):
```suggestion
class ns_basic_personal_amount(Variable):
```

2023-08-03 02:33 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/basic_personal_credits.py
rename to `basic_personal_amount`

2023-08-08 01:59 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/applicable_rate.yaml
> +description: Nova Scotia reduces its additional basic personal amount out at this rate.
```suggestion
description: Nova Scotia phases its additional basic personal amount out at this rate.
```

2023-08-08 02:00 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/applicable_rate.yaml
> +    href: https://hr.acadiau.ca/files/sites/hr/Payroll/Pensions%20&%20Benefits/NS_TD1_2022.pdf
```suggestion
    href: https://hr.acadiau.ca/files/sites/hr/Payroll/Pensions%20&%20Benefits/NS_TD1_2022.pdf#page=1
```

2023-08-08 02:01 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/additional_amount.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5003-d/5003-d-22e.pdf
add Nova Scotia income tax act as another reference

2023-08-08 02:01 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/additional_amount.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5003-d/5003-d-22e.pdf
all yaml files

2023-08-09 00:52 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/additional_amount.yaml
> +    href: https://hr.acadiau.ca/files/sites/hr/Payroll/Pensions%20&%20Benefits/NS_TD1_2022.pdf
```suggestion
    href: https://hr.acadiau.ca/files/sites/hr/Payroll/Pensions%20&%20Benefits/NS_TD1_2022.pdf#page=1
```

2023-08-10 02:36 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/additional_amount.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5003-d/5003-d-22e.pdf
add page number

2023-08-10 02:36 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/additional_amount.yaml
> +  - title: Worksheet NS428
```suggestion
  - title: 2022 Worksheet NS428
```

2023-08-10 02:36 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/additional_amount.yaml
> +  - title: Worksheet NS428
same for all yaml files

2023-08-10 02:37 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/lower_income_threshold.yaml
rename to `income_threshold.yaml`

2023-08-10 02:37 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/additional_amount.yaml
> +  - title: Nova Scotia income tax act
add section of the income tax act where this can be found

2023-08-15 15:10 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount.py
> +        exceedance = taxable_income - p.additional_amount.income_threshold
```suggestion
        exceedance = max_(taxable_income - p.additional_amount.income_threshold, 0)
```

2023-08-15 15:11 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount.yaml
> +    total_individual_pre_tax_income: 76_000
```suggestion
    total_individual_pre_tax_income: 75_001
```

2023-08-16 21:23 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/applicable_rate.yaml
> +  rate_unit: /1
```suggestion
```

2023-08-16 21:24 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/applicable_rate.yaml
> +  unit: currency-CAD
```suggestion
  unit: /1
```

2023-08-16 21:24 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/applicable_rate.yaml
we can combine the rate and the income threshold into one single amount parameter 

then use the .calc function in the .py file

2023-08-29 17:43 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/max_amount.yaml
> +      values:
dont need values in rate or threshold

2023-08-29 17:43 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount.py
> +        reduced_additional_amount = (
include the max_ function here

2023-08-29 17:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Nova Scotia Basic Personal Amount
```suggestion
    - Nova Scotia Basic Personal Amount.
```

2023-08-30 00:58 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount.yaml
> +    total_individual_pre_tax_income: 27_000
```suggestion
    total_individual_pre_tax_income: 25_000
```

2023-08-30 01:02 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/base.yaml
> +  2022-01-01: 8_481
i dont think you are using this, this should be $11,481

2023-09-04 23:16 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/base.yaml
add one more parameter called additional - for the $8,481

2023-09-04 23:21 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount.py
> +        # Calculate additional amount added to base amount
return where(income >= 25,000, 11,825, 8,481 - 3,000(reduced if need))

2023-09-09 23:58 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount.py
> +    # p.base + additional_amount
```suggestion
```

2023-09-09 23:58 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Nova Scotia Basic Personal Amount.
```suggestion
    - Nova Scotia basic personal amount.
```

2023-09-10 00:02 UTC, PavelMakarchuk approved these changes

2023-09-29 23:29 UTC, MaxGhenis requested changes

2023-09-29 23:29 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/income_threshold.yaml
> +description: Nova Scotia lower income threshold for maximum basic personal amount in basic personal amount.
rephrase like other descriptions - though is this parameter needed? It's not in the formula

2023-09-29 23:29 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_basic_personal_amount.py
> +        return (p.base + reduced_additional_amount,)
```suggestion
        return p.base + reduced_additional_amount
```

2023-10-06 11:21 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/basic_personal_amount/additional_amount/income_threshold.yaml
> +description: Nova Scotia lower income threshold for maximum basic personal amount in basic personal amount.
This was not resolved

2026-07-07 13:28 UTC, MaxGhenis commented
Thank you for this — the Nova Scotia basic personal amount is a real gap in the model and your values are right ($8,481 base plus the $3,000 additional amount phasing out between $25,000 and $75,000). The PR stalled on an unresolved question about the income-threshold parameter and the phase-out formula, and main has since moved on: the changelog switched to towncrier fragments, the formatter to ruff, and the branch now conflicts. Rather than untangle a two-year-old branch, we'll re-implement the NS BPA fresh using your values and references as the starting point — the gap stays tracked in #395. Closing this PR; thanks for the careful research.

2026-07-07 13:28 UTC, closed without merging