SK Disability amount
PolicyEngine/policyengine-canada pull request #415
Opened 2023-07-31 17:51 UTC by Yaohhhh

Fixed #370

2023-08-03 21:19 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/sk/tax/income/credits/sk_disability_amount/amount.yaml
> +description: Saskatchewan provides this tax-credit amount for the qualified disabled.
```suggestion
description: Saskatchewan provides this amount for qualified disabled filers under the saskatchewan disability amount.
```

2023-08-03 21:20 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/sk/tax/income/credits/sk_disability_amount/amount.yaml
> +  2023-01-01: 10_405
need 2022 value + 2022 form

2023-08-03 21:20 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/sk_disability_amount/sk_disability_amount.py
> +        eligibility = person("is_disable_certificate", period)
```suggestion
        eligibility = person("is_disabled", period)
        head = person("is_head", period)
```

2023-08-03 21:21 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/sk_disability_amount/sk_disability_amount.py
> +        return where(eligibility == 1, p.amount, 0)
```suggestion
        return where(eligibility, p.amount, 0)
```

2023-08-03 21:21 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/sk_disability_amount/is_disable_certificate.py
dont need this

2023-08-03 21:22 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/sk_disability_amount/sk_disability_amount.py
> +    label = "SK Disability Amount Tax Credit"
```suggestion
    label = "Saskatchewan Disability Amount Tax Credit"
```

2023-08-03 21:22 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/sk_disability_amount/sk_disability_amount.py
> +    definition_period = YEAR
add: unit: CAD

2023-08-03 21:22 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Sk Disability amount tax credit.
```suggestion
    - Saskatchewan Disability amount.
```

2023-08-03 21:22 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/sk/tax/income/credits/sk_disability_amount/amount.yaml
> +  label: Saskatchewan disability tax credit amount
```suggestion
  label: Saskatchewan disability amount
```

2023-08-03 23:10 UTC, PavelMakarchuk approved these changes

2023-08-04 20:23 UTC, MaxGhenis requested changes

2023-08-04 20:23 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/sk/tax/income/credits/disability_amount/amount.yaml
> +  - title: 2023 Saskatchewan TD1SK Personal Tax Credits Return
and elsewhere
```suggestion
  - title: 2023 Saskatchewan TD1SK Personal Tax Credits Return, line 5
```

2023-08-04 20:23 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/sk/tax/income/credits/disability_amount/amount.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1sk/td1sk-23e.pdf
and elsewhere
```suggestion
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1sk/td1sk-23e.pdf#page=1
```

2023-08-04 20:23 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/sk/tax/income/credits/disability_amount/amount.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1sk/td1sk-22e.pdf
Cite legal code or leave a comment saying it's unavailable

2023-08-04 20:23 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/disability_amount/sk_disability_amount.py
> +    unit: CAD
```suggestion
    unit = CAD
```

2023-08-04 20:23 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/disability_amount/sk_disability_amount.py
> +    label = "Saskatchewan Disability Amount Tax Credit"
```suggestion
    label = "Saskatchewan disability amount tax credit"
```

2023-08-04 20:23 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/disability_amount/sk_disability_amount.py
> +        eligbile = is_head & disabled
```suggestion
        eligible = is_head & disabled
        return eligible * p.amount
```

2023-08-09 17:27 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/disability_amount/sk_disability_amount.py
> +        is_head = person("is_head", period)
```suggestion
```

2023-08-09 17:27 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/disability_amount/sk_disability_amount.py
> +        eligbile = is_head & disabled
```suggestion
```

2023-08-09 17:27 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/disability_amount/sk_disability_amount.py
> +        return eligible * p.amount
```suggestion
        return disabled * p.amount
```

2023-08-09 17:28 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/sk/tax/income/credits/disability_amount/amount.yaml
> +    href: https://pubsaskdev.blob.core.windows.net/pubsask-prod/806/I2-01.pdf
add page number to pdf here

2023-08-10 20:37 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/sk/tax/income/credits/disability_amount/sk_disability_amount.py
> +        eligible = is_head & disabled
```suggestion
```

2023-08-16 16:40 UTC, PavelMakarchuk approved these changes

2023-08-18 03:48 UTC, MaxGhenis approved these changes

2023-08-18 03:48 UTC, merged