Alberta Disablity Credit
PolicyEngine/policyengine-canada pull request #439
Opened 2023-09-07 22:29 UTC by 7qiwx

Fixes #329

2023-09-14 22:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +  name: Alberta disability credit.
```suggestion
```

2023-09-14 22:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +  label: Alberta disability credit amount.
```suggestion
  label: Alberta disability credit amount
```

2023-09-14 22:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +  - title: Alberta personal tax credits return
name to file title

2023-09-14 22:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1ab/td1ab-23e.pdf
add pdf page

2023-09-14 22:32 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit_eligible.py
> +    label = "Alberta disability tax credit eligbility"
```suggestion
    label = "Eligible for the Alberta disability tax credit"
```

2023-09-14 22:32 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1ab/td1ab-23e.pdf
```suggestion
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1ab/td1ab-23e.pdf#page=1
```

2023-09-14 22:32 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +  - title: Alberta disability credit base amount (Page 1 Section 4)
```suggestion
  - title: Alberta disability credit base amount - Section 4
```

2023-09-19 19:02 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +  - title: Alberta disability credit base amount - Section 4
add the Alberta law - income tax law document

2023-10-12 22:13 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +  2022-01-01: 16_201
```suggestion
  2022-01-01: 15_284
  2023-01-01: 16_201
```

2023-10-12 22:13 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1ab/td1ab-23e.pdf#page=1
add this reference: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5009-d/5009-d-22e.pdf

2023-10-12 22:15 UTC, PavelMakarchuk commented on changelog_entry.yaml
need to add calculation from: 

https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5009-d/5009-d-22e.pdf

2023-10-12 22:17 UTC, PavelMakarchuk commented on changelog_entry.yaml
create a variable named `childcare_received` in 
policyengine_canada/variables/household/expenses/childcare/

2023-10-23 13:13 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/eligible_age.yaml
> +    href:  https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5009-d/5009-d-22e.pdf
```suggestion
    href:  https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5009-d/5009-d-22e.pdf#page=2
```

2023-10-23 13:13 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/eligible_age.yaml
> +    href:  https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5009-d/5009-d-22e.pdf
all pdf sources in yaml files

2023-10-23 13:14 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/max_amount_child.yaml
> +description: Alberta provides this maximum amount for child under 18 under disability credit.
```suggestion
description: Alberta provides this maximum disability credit amount for children under a certain age threshold.
```

2023-10-23 13:14 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/max_amount_child.yaml
> +  label: Alberta disability credit max amount
```suggestion
  label: Alberta disability credit younger max amount
```

2023-10-23 13:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/max_amount_total.yaml
> +  label: Alberta disability credit max amount
```suggestion
  label: Alberta disability credit max base amount
```

2023-10-23 13:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/threshold.yaml
> +description: Alberta provides this threshold under disability credit.
delete extra line (1)

2023-10-23 13:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/threshold.yaml
rename to income threshold

2023-10-23 13:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/threshold.yaml
> +  label: Alberta disability credit threshold
```suggestion
  label: Alberta disability credit income threshold
```

2023-10-23 13:16 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/eligible_age.yaml
> +  unit: year
```suggestion
  unit: year
  period: year
```

2023-10-23 13:16 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +description: Alberta provides this amount under the disability credit.
```suggestion
description: Alberta provides this base disability credit amount. 
```

2023-10-23 13:16 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/base.yaml
> +  label: Alberta disability credit amount
```suggestion
  label: Alberta disability credit base amount
```

2023-10-23 13:17 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit.py
> +        child_credit = (person("age", period) < p.eligible_age) * max(
separate the formula out into multiple steps

2023-10-23 13:17 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit.py
> +        # max_amount_child - (childcare_received - threshold)
delete extra code if not needed

2023-10-23 13:17 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit.py
> +        return min(p.max_amount_total, p.base + child_credit)
```suggestion
        return min_(p.max_amount_total, p.base + child_credit)
```

2023-10-23 13:17 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit.py
> +        child_credit = (person("age", period) < p.eligible_age) * max(
```suggestion
        child_credit = (person("age", period) < p.eligible_age) * max_(
```

2023-10-23 13:17 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit.py
> +            0, p.max_amount_child - max(0, childcare_received - p.threshold)
```suggestion
            0, p.max_amount_child - max_(0, childcare_received - p.threshold)
```

2023-10-23 13:17 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit_eligible.yaml
> +
delete extra lines

2023-10-31 19:11 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/eligible_age.yaml
> +  - title: Alberta Disablitiy credit - Page 2
try to find this program in the Alberta income tax act - and leave a comment if the program or parts of it are not represented there

2023-10-31 19:13 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit.py
> +        childcare = max_(0, childcare_received - p.income_threshold)
```suggestion
        additional_amount_reduction = max_(0, childcare_received - p.income_threshold)
```

2023-10-31 19:13 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit.py
> +        child_credit_eligibility = person("age", period) < p.eligible_age
```suggestion
        additional_amount_eligibility = person("age", period) < p.eligible_age
```

2023-10-31 19:14 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_tax_credit.py
> +        child_credit = (
```suggestion
        max_additional_amount =  max_(0, p.max_amount.younger - childcare)
        additional_amount = where(additional_amount_eligibile, max_additional_amount, 0)
```

2023-10-31 19:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/eligible_age.yaml
> +  label: Alberta disability credit age eligibility
```suggestion
  label: Alberta disability credit additional amount age eligibility
```

2023-10-31 19:16 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/income_threshold.yaml
> +description: Alberta provides this threshold under disability credit.
```suggestion
description: Alberta reduces the additional disability credit amount by the excess of childcare expenses over this threshold.
```

2023-10-31 19:16 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/eligible_age.yaml
make a folder called `additional_amount` - everything but base

2023-10-31 19:17 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/max_amount_total.yaml
> +description: Alberta limits the disability credit to this maximum base amount.
```suggestion
description: Alberta limits the disability credit to this maximum base amount.
```

2023-10-31 19:17 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/max_amount_total.yaml
> +  label: Alberta disability credit max base amount
```suggestion
  label: Alberta disability credit max amount
```

2023-10-31 19:17 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/disability/max_amount/younger.yaml
> +description: Alberta provides this maximum disability credit amount for children under a certain age threshold.
```suggestion
description: Alberta provides this additional disability credit amount for younger filers.
```

2024-02-02 00:14 UTC, PavelMakarchuk requested changes

2024-02-16 01:17 UTC, MaxGhenis requested changes

2024-02-16 01:17 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/on/tax/income/credits/oeptc/oeptc_category.py
> +    label = "oeptc category"
```suggestion
    label = "OEPTC category"
```

2024-02-16 01:17 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_credit.py
> +        total_credit_amount = p.base + additional_amount
```suggestion
        uncapped_amount = p.base + additional_amount
```

2024-02-18 06:38 UTC, MaxGhenis commented on policyengine_canada/variables/household/person/care_expenses.py
> +    label = "Amount of childcare expenses incurred by the child"
So we can include elder and disability care in it
```suggestion
    label = "Amount of care expenses incurred by the person"
```

2024-02-19 13:50 UTC, MaxGhenis requested changes
can we hook this up to the net income tree?

2024-02-19 13:50 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/disability/ab_disability_credit_additional_amount.py
> +        reduced_childcare_expenses = max_(
More conventional term
```suggestion
        excess_childcare_expenses = max_(
```

2024-02-21 14:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
could you create an ab_refundable / ab_non_refundable credits python and respective refundable.yaml and non_refundable.yaml files 
This is the income tree structure which we need to integrate the program

2024-02-21 14:44 UTC, PavelMakarchuk commented on changelog_entry.yaml
add the credit which we have created here to the right parameter file

2024-02-23 00:56 UTC, PavelMakarchuk requested changes

2024-02-23 00:56 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/non_refundable.yaml
> +  unit: program
```suggestion
  unit: list
  period: year 
  label: Alberta non-refundable credits
```

2024-02-23 00:56 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/non_refundable.yaml
> +description: Alberta list of non-refundable tax credits.
```suggestion
description: Alberta provides the follwoing non-refundable tax credits.
```

2024-02-23 00:56 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/non_refundable.yaml
> +  unit: program
also add reference (tax form and law) - general for the credits

2024-02-23 00:56 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/refundable.yaml
> +  unit: program
same adjustments as in non-ref.

2024-02-23 00:56 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/refundable.yaml
> +  2022-01-01:
```suggestion
  2022-01-01: []
```

2024-02-23 00:56 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/refundable.yaml
> +description: Alberta list of refundable tax credits.
same as non-ref.

2024-02-23 00:56 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/ab_non_refundable_credits.py
> +    entity = Person
```suggestion
    entity = Household
```

2024-02-23 15:41 UTC, MaxGhenis approved these changes

2024-02-23 15:41 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/non_refundable.yaml
> +description: Alberta provides the follwoing non-refundable tax credits.
```suggestion
description: Alberta provides the following non-refundable tax credits.  
```

2024-02-24 05:08 UTC, merged