Yukon-Basic-Personal-Amount
PolicyEngine/policyengine-canada pull request #441
Opened 2023-09-11 22:12 UTC by sqw0418

Fixes #312

2023-09-11 22:13 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/amount.yaml
> +description: Yukon credits basic personal amount, based on the filers income.
```suggestion
description: Yukon credits this basic personal amount, based on the filers income.
```

2023-09-11 22:13 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/amount.yaml
> +      2023-01-01: 235_675 # 165_430 + 70_245
check logic - check form and legal code

2023-09-11 22:13 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/amount.yaml
> +    rate:
we want to split this up into the parameters of the form

2023-09-11 22:14 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/amount.yaml
> +      2022-01-01: 14_398
```suggestion
      2022-01-01: 0
```

2023-09-11 22:14 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/amount.yaml
> +    rate:
keep this at reduction with rates and make a max amount file

2023-09-11 22:14 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.yaml
> +- name: Not head
dont need this test

2023-10-04 22:48 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/yt_basic_personal_amount.py
> +        eligible = (division - (individual_net_income - income_threshold)) <= 0
```suggestion
        additional_amount_eligible = (division - (individual_net_income - income_threshold)) <= 0
```

2023-10-04 22:48 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/yt_basic_personal_amount.py
> +        eligible_amount = division - (individual_net_income - income_threshold)
```suggestion
        additional_amount = division - (individual_net_income - income_threshold)
```

2023-10-04 22:48 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/yt_basic_personal_amount.py
> +        division = p.division
```suggestion
        divisor = p.division
```

2023-10-04 22:50 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/yt_basic_personal_amount.py
> +        eligible = (division - (individual_net_income - income_threshold)) <= 0
put additional amount on top of the eligibility

2023-10-04 22:50 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/yt/tax/income/yt_basic_personal_amount.py
> +        income_threshold = p.income_threshold
```suggestion
```

2023-10-04 22:51 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +description: Yukon credits this basic personal amount, based on the base amount
rewrite the descriptions

2023-10-04 22:51 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +  label: Yukon income basic personal base amount
rewrite labels

2023-10-04 22:51 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +  - title: Income Tax Act
add section of income tax act

2023-10-04 22:51 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +    href: https://laws.yukon.ca/cms/images/LEGISLATION/PRINCIPAL/2002/2002-0118/2002-0118.pdf
add page

2023-10-04 22:51 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +  - title: Income Tax Act
all yaml

2023-10-04 22:51 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +    href: https://laws.yukon.ca/cms/images/LEGISLATION/PRINCIPAL/2002/2002-0118/2002-0118.pdf
all yaml

2023-10-04 22:51 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +  label: Yukon income basic personal base amount
all yaml

2023-10-04 22:51 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +description: Yukon credits this basic personal amount, based on the base amount
all yaml

2023-10-04 22:52 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/yt/tax/income/credits/yt_basic_personal_amount.yaml
> +
delete extra lines

2023-10-04 22:53 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/division.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1yt/td1yt-22e.pdf#page=1
delete all sources which do not directly reference the number

2023-10-04 22:53 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/division.yaml
> +    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1yt/td1yt-22e.pdf#page=1
all yaml files

2023-10-04 22:53 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/division.yaml
rename to divisor.yaml

2023-10-09 22:13 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +  - title: Worksheet for the Yukon 2023 Personal Tax Credits Return
add 2022 reference and double check values

2023-10-09 22:15 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +  2022-01-01: 1_479
```suggestion
  2022-01-01: 1_679
  2023-01-01: 1_479
```

2023-10-09 22:17 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +  - title: Worksheet for the Yukon 2023 Personal Tax Credits Return
leave the law reference and add a comment: # The credit amount is not mentioned in the Yukon income tax act

https://laws.yukon.ca/cms/images/LEGISLATION/PRINCIPAL/2002/2002-0118/2002-0118.pdf

2023-10-09 22:18 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +  - title: Worksheet for the Yukon 2023 Personal Tax Credits Return
for every yaml file in this PR

2023-10-09 22:19 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/base_amount.yaml
> +description: Yukon credits this basic personal amount, based on this base amount
```suggestion
description: Yukon credits this base basic personal amount.
```

2023-10-09 22:19 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/divisor.yaml
> +description: Yukon credits basic personal amount, this is divisor for the calculation
```suggestion
description: Yukon divides the basic personal amount by this amount.
```

2023-10-09 22:20 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/divisor.yaml
> +  label: Yukon income basic personal divisor amount
```suggestion
  label: Yukon income basic personal divisor
```

2023-10-09 22:21 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/income_threshold.yaml
> +description: Yukon credits this basic personal amount, based on the income threshold
```suggestion
description: Yukon reduces the basic personal amount for filers with income above this threshold.
```

2023-10-09 22:22 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/income_threshold.yaml
> +  label: Yukon income threshold of basic personal amount
```suggestion
  label: Yukon basic personal amount reduction income threshold
```

2023-10-09 22:22 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +description: Yukon credits this basic personal amount, based on this applicable amount
```suggestion
description: Yukon reduces this basic personal amount, for high income filers.
```

2023-10-09 22:22 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +  label: Yukon income applicable amount
```suggestion
  label: Yukon basic personal amount applicable amount
```

2023-10-18 22:40 UTC, PavelMakarchuk approved these changes

2023-10-20 04:08 UTC, MaxGhenis requested changes

2023-10-20 04:08 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/applicable_amount.yaml
> +description: Yukon reduces this basic personal amount, for high income filers.
Isn't this the amount of the additional bpa?

2023-10-20 04:08 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/yt/tax/income/credits/basic_personal_amount/divisor.yaml
this is the phase-out width

2023-11-16 16:17 UTC, PavelMakarchuk requested changes
Max left comments, I dont see any commits resolving those

2024-05-10 14:22 UTC, closed without merging