Nova Scotia Pension Amount
PolicyEngine/policyengine-canada pull request #474
Opened 2023-12-03 16:23 UTC by okeyiii

Thanks for contributing! Please remove any top-level sections that do not apply to your changes.

- [ ] `make format && make documentation` has been run.

Add pension amount for Nova Scotia

2023-12-03 22:25 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/pension_income_amount/max_amount.yaml
> +  - title: Nova Scotia income tax act - subdivision c - Deduction for employment out of Canada
more precise reference point

2023-12-03 22:26 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/pension_income_amount/max_amount.yaml
> +  2022-01-01: 1_173
```suggestion
  2017-01-01: 1_173
```

2023-12-03 22:26 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/pension_income_amount/max_amount.yaml
> +  label: Nova Scotia pension income amount max amount
```suggestion
  label: Nova Scotia pension income amount cap
```

2023-12-03 22:26 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/ns/tax/income/credits/ns_pension_income_amount
add .yaml

2023-12-03 22:26 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_pension_income_amount
add .py

2023-12-03 22:26 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_pension_income_amount
> +    label = "Nova Scotia Pension Income Amount"
```suggestion
    label = "Nova Scotia pension income amount"
```

2023-12-03 22:27 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_pension_income_amount
> +        return min(pension_income_amount, max_amount)
```suggestion
        return min_(pension_income_amount, max_amount)
```

2023-12-03 22:27 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/ns/tax/income/credits/ns_pension_income_amount
add one more test with 0

2023-12-10 22:09 UTC, PavelMakarchuk approved these changes

2023-12-11 04:54 UTC, MaxGhenis requested changes
Can you also hook it up to the net income tree?

2023-12-11 04:54 UTC, MaxGhenis commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_pension_income_amount.py
> +        cap = parameters(
our convention, then `p.cap`
```suggestion
        p = parameters(
            period
        ).gov.provinces.ns.tax.income.credits.pension_income_amount
```

2023-12-11 04:54 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/pension_income_amount/cap.yaml
> +  - title: 2022 Nova Scotia Personal Tax Credits Return
```suggestion
  - title: 2022 Nova Scotia Personal Tax Credits Return Line 3
```

2024-01-17 23:02 UTC, PavelMakarchuk requested changes

2024-01-17 23:02 UTC, PavelMakarchuk commented on changelog_entry.yaml
link to the issue in the PR description

2024-01-17 23:02 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_pension_income_amount.py
> +        return min_(pension_income_amount, cap)
```suggestion
        return min_(pension_income_amount, p.cap)
```

2024-01-17 23:02 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ns/tax/income/credits/ns_pension_income_amount.py
> +        cap = p.cap
```suggestion
```

2024-01-17 23:02 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/pension_income_amount/cap.yaml
is there an age restriction for this credit?

2024-02-01 23:17 UTC, okeyiii commented on policyengine_canada/parameters/gov/provinces/ns/tax/income/credits/pension_income_amount/cap.yaml
https://www.nspssp.ca/members/your-working-years/pension-benefit/how-your-pension-calculated

2024-02-01 23:38 UTC, PavelMakarchuk commented
> again please hook up to net income tree

@MaxGhenis we will create a new PR to create the net income tree of NS once the open PR's are merged, since we have not followed this practice early in the development the credits are scattered in the repo. 
@okeyiii and I thought this would be the best approach to have a clean PR for province income tree structures that can then be used as a reference for other devs.

2024-02-02 06:53 UTC, MaxGhenis approved these changes

2024-02-02 06:53 UTC, merged