Alberta base personal credit
PolicyEngine/policyengine-canada pull request #486
Opened 2024-04-16 01:53 UTC by SirMalamute

Fixes #376

Thanks for contributing! Please remove any top-level sections that do not apply to your changes.

- [ ] `make format && make documentation` has been run.

# New variable

- [ ] Label field added
- [ ] Documentation field added
- [ ] Unit field added
- [ ] Default value field added if relevant
- [ ] Variable name follows conventions
- [ ] Unit test(s) added
- [ ] Integration test(s) added if relevant
- [ ] Issues this PR fixes linked

## What's changed

Description of the changes here.

# Bug fix

- [ ] Regression test added
- [ ] Regression test passing

## What this fixes and how it's fixed

Description of how this fix works goes here. Link any issues this PR fixes.

2024-04-17 20:35 UTC, PavelMakarchuk requested changes

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/ab_base_personal_credit.py
> +        base = parameters(period).gov.provinces.ab.tax.income.credits.base
```suggestion
        return parameters(period).gov.provinces.ab.tax.income.credits.base
```

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/base.yaml
> +  label: Alberta base personal credit maximum amount
```suggestion
  label: Alberta basic personal amount
```

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/base.yaml
make folder called basic_personal_amount and rename this file to amount.yaml

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/base.yaml
> +description: Alberta provides this maximum amount under the personal credit.
```suggestion
description: Alberta provides this basic personal amount. 
```

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/base.yaml
> +  2023-01-01: 21_003
add 2022 value

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/base.yaml
> +  - title: Alberta income tax personal credit
add 2022 reference + legal code

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/ab_base_personal_credit.py
> +class ab_base_personal_credit(Variable):
```suggestion
class ab_basic_personal_amount(Variable):
```

2024-04-17 20:35 UTC, PavelMakarchuk commented on changelog_entry.yaml
add the credit to the list of non refundable credits

2024-04-17 20:35 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Alberta base personal income credit.
```suggestion
    - Alberta basic personal amount.
```

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/ab_base_personal_credit.py
> +    label = "Alberta base personal credit"
```suggestion
    label = "Alberta basic personal amount"
```

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/tests/gov/provinces/ab/tax/income/credits/base.yaml
rename test file to ab_basic_personal_amount.yaml

2024-04-17 20:35 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/ab_base_personal_credit.py
> +class ab_base_personal_credit(Variable):
also rename var

2024-04-17 22:28 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/base.yaml
make a `basic_personal_amount` folder and rename this to amount.yaml

2024-04-21 22:08 UTC, PavelMakarchuk requested changes

2024-04-21 22:08 UTC, PavelMakarchuk commented on policyengine_canada/variables/gov/provinces/ab/tax/income/credits/ab_base_personal_credit.py
> +        return base
```suggestion
```

2024-04-22 20:22 UTC, PavelMakarchuk approved these changes

2024-04-22 23:19 UTC, MaxGhenis approved these changes

2024-04-22 23:19 UTC, MaxGhenis commented on policyengine_canada/parameters/gov/provinces/ab/tax/income/credits/basic_personal_amount/amount.yaml
> +  2022-01-01: 19_369
```suggestion
  # Legal code defines $19,369.
  # Section 44.2 defines indexing.
  2022-01-01: 19_369
```

2024-04-22 23:27 UTC, merged