Update the Climate Action Incentive Payment Structure 2023-2024
PolicyEngine/policyengine-canada pull request #500
Opened 2024-10-24 15:58 UTC by londonpatel

Fixes #499

2024-10-27 19:48 UTC, PavelMakarchuk requested changes

2024-10-27 19:48 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/cra/tax/income/credits/climate_action_incentive/amount.yaml
> +ELDEST_CHILD_IN_SINGLE_PARENT_HOUSEHOLD: #can cut the down and do each child now
```suggestion
ELDEST_CHILD_IN_SINGLE_PARENT_HOUSEHOLD: 
```

2024-10-27 19:48 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/cra/tax/income/credits/climate_action_incentive/amount.yaml
> +ELDEST_CHILD_IN_SINGLE_PARENT_HOUSEHOLD: #can cut the down and do each child now
Will add it as a comment once we have the adjustment

2024-10-27 19:48 UTC, PavelMakarchuk commented on policyengine_canada/parameters/gov/cra/tax/income/credits/climate_action_incentive/amount.yaml
please add the new value to rural.yaml

2024-12-09 17:07 UTC, PavelMakarchuk approved these changes

2024-12-09 18:11 UTC, MaxGhenis commented
test failing

2026-07-07 13:28 UTC, MaxGhenis commented
Thanks for putting this together. Since this PR was opened, the climate action incentive amounts for 2023-24 and 2024-25 have been implemented on main across all provinces — including the rural supplement and the Canada Carbon Rebate renaming — so the structure updated here is now fully covered (the ON $488 / AB $772 2023-24 amounts on main match the Department of Finance releases). Closing as superseded by main. Really appreciate the contribution.

2026-07-07 13:28 UTC, closed without merging